services:
  mongodb:
    image: mongo:6.0.23
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: administrator
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./config/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: administrator
      ME_CONFIG_MONGODB_URL: mongodb://root:administrator@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-data: